### ISSUE TITLE
iPhone 5s Dualboot "Attaching" Hang

### ISSUE THREAD

**Issue by eatingurtoes** [MatthewPierson/Divise#10]
I download the RootFS, and then when I press "Dualboot Device!", it hangs on "Attaching...".

**Comment by MatthewPierson** [comment]
I need more information to help you. What is the iOS of the device and what is the iOS you are trying to dualboot?

**Comment by eatingurtoes** [comment]
I am on an iPhone 5s (iPhone6,1) running iOS 12.4.7, jailbroken with checkra1n, and I am attempting to dualboot 12.4.

**Comment by MatthewPierson** [comment]
Does the issue persist if you delete the downloaded RootFS.dmg and redownload it?

**Comment by eatingurtoes** [comment]
@MatthewPierson I tried that before I posted, it does persist.

**Comment by eatingurtoes** [comment]
@MatthewPierson UPDATE - I got it to dualboot, but PyBoot keeps acting up.

**Comment by Litteeen** [comment]
@eatingurtoes hiya, may i ask what kept it from dualbooting? 😊

**Comment by eatingurtoes** [comment]
@Litteeen I updated my Divisé version and it worked perfectly.

**Comment by Litteeen** [comment]
@eatingurtoes hmm i see, i'm using the latest version, but a local IPSW instead of a downloaded one, i'll try a different one and a different device, thanks for letting me know ^^

**Comment by zyan910** [comment]
I’m facing the same issue @MatthewPierson 

iPhone 8 13.5 jailbroken w unc0ver. 
Attempting to install iOS 14.0 b1 with local ipsw. 
Divisé version - 1.0.3.1

**Comment by Litteeen** [comment]
@zyan910 iOS 14 isn’t compatible yet

**Comment by zyan910** [comment]
Why do you say so? Curiously asking

**Comment by Litteeen** [comment]
i have already talked to matty about it

**Comment by MatthewPierson** [comment]
@zyan910 Can confirm, 14.0 beta dualboots are not working currently. Am working on it but don't expect anything for a while

**Comment by zyan910** [comment]
Alr I see, Thanks :D 

Please help me out to remove the partitions made by Divisé in attempts to dual boot since it’s there and talking up space in my phone I’ve posted an issue about it too.
