### ISSUE TITLE
iOS 1.1.1???

### ISSUE THREAD

**Issue by CE1CECL** [MatthewPierson/Divise#11]
Whenever I go to Divisé, I always see my second partition of iOS is always 1.1.1 and it’s actually 10.3.3 (btw I used a predownloaded ipsw from ipsw.me) I am doing this on iPhone 6s. Is this a bug?
![05F41EA0-5672-4D87-B04A-8DA155F3ED48](https://user-images.githubusercontent.com/52040854/83931716-31adc600-a76c-11ea-9f35-77a526acc2a3.png)
![6AE583D0-DA8B-40B1-913F-C4F180577FDC](https://user-images.githubusercontent.com/52040854/83931722-37a3a700-a76c-11ea-8a07-98ab18bed1b3.png)
![777D9678-E110-41F3-AC64-30CEDBEF3861](https://user-images.githubusercontent.com/52040854/83931727-3bcfc480-a76c-11ea-9267-4ab4edb0204c.png)

**Comment by MatthewPierson** [comment]
That is a bug. 1.1.1 is the default value that should get replaced with the version found in the second OS's SystemVersion.plist (when using a locally downloaded IPSW). It's not a huge issue, but if you wanted to manually change the value just edit the plist at "/var/mobile/Library/Preferences/com.moski.dualboot.plist" and replace 1.1.1 with whatever versions you dualbooted. 

Will look into why this happened though, thought I fixed it before release
