### ISSUE TITLE
Excuse me?

### ISSUE THREAD

**Issue by luixiuno** [MatthewPierson/Divise#16]
Why when i try to multiboot it says delete iPad?, WTF I mean I don’t wanna lose my data or my iOS because if the jailbreakable version is unsigned and my iOS is bricked, now I gotta install a jailed iOS

**Comment by luixiuno** [comment]
I said multiboot, not delete iPad and downgrade to a old iOS

**Comment by UInt2048** [comment]
@luixiuno Might be lingering from SuccessionRestore...

**Comment by UInt2048** [comment]
Ignore the "Erase iPad" prompt - it actually won't erase anything
