### ISSUE TITLE
-

### ISSUE THREAD

**Issue by cuj** [MatthewPierson/Divise#38]
>

**Comment by Visualwit** [comment]
What Version Are You Trying To Install?

**Comment by cuj** [comment]
> What Version Are You Trying To Install?

iOS 10.0.1

**Comment by Visualwit** [comment]
I See You Are Running iOS 14 With It's SEP Is Not Compatible With iOS 10, 11, & 12, It's Not Possible, Try Dualbooting With iOS 13 Instead!

**Comment by eliekh05** [comment]
same issue but im on iOS 12.5.5 and installing iOS 10.0.1
