### ISSUE TITLE
iOS 10 & 11 DualBoot iPad Air 1

### ISSUE THREAD

**Issue by Visualwit** [MatthewPierson/Divise#41]
I Have iOS 10.3.3 On My iPad Air 1 & I've Successfully DualBooted It With iOS 11.0 And After Booting, Wifi & Bluetooth Don't Work, iTunes Fails To Connect To The iPad With The Error: "The Value Is Missing" HELP!

**Comment by Visualwit** [comment]
I Have Another iPad Air 1 & I DualBooted iOS 12.5.3 With iOS 11.4 And Everything Works, IDK What's Wrong With iOS 10?

**Comment by MatthewPierson** [comment]
iOS 10.3.3's SEP causes a lot of issues when dual booted with iOS 11. Nothing you can do about it sorry.
