### ISSUE TITLE
iPad 7th booting issue

### ISSUE THREAD

**Issue by kinkenyuen** [MatthewPierson/Divise#9]
![Xnip2020-06-05_11-56-18](https://user-images.githubusercontent.com/41050490/83835548-a4df1a00-a723-11ea-8918-0e6707b0218f.jpg)
![Xnip2020-06-05_11-56-46](https://user-images.githubusercontent.com/41050490/83835557-ac9ebe80-a723-11ea-91d2-5cad1f028d4a.jpg)

File mismatch

**Comment by MatthewPierson** [comment]
Some iPads are known to have issues with PyBoot which will be fixed soon. Also please open this as an issue in the PyBoot repo next time, not here. PyBoot and Divisé are two separate things

**Comment by kinkenyuen** [comment]
thanks
